# Generated by Django 5.1.1 on 2024-10-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
